name: Windows CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
		
jobs:
  build:
     runs-on: windows-latest

	steps:
	  - name: Checkout repository
	    uses: actions/checkout@v2

	  - name: Set up JDK 11
	    uses: actions/setup-java@v2
	    with:
	      java-version: '11'
	      distribution: 'temurin'

	  - name: Compile TinyEdit.java
	    run: javac TinyEdit.java

	  - name: Run TinyEdit
	    run: java TinyEdit

	  - name: Download Checkstyle
	    run: |
	    curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.1/checkstyle-10.12.1-all.jar

	  - name: Check code formatting
	    run: java -jar checkstyle.jar -c /google_checks.xml TinyEdit.java

	  - name: Lint code
	    run: java -jar checkstyle.jar -c /google_checks.xml TinyEdit.java
